<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_name</name>
   <tag></tag>
   <elementGuidId>cbc6f120-1234-4974-8b96-0f811e6553f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = concat(&quot;//*[@name=&quot; , &quot;'&quot; , &quot;Name&quot; , &quot;'&quot; , &quot;]&quot;) and @placeholder = 'First Name' and @type = 'text' and @class = 'firstName compoundBorderBottom form-element__row input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;Name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8cd5f3f-b724-4888-97aa-a1ea935ec48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>6f3de488-375f-43fd-bdcf-17d6d7de58ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>//*[@name='Name']</value>
      <webElementGuid>e6e9cf2d-7830-46ce-9f65-1be878a1dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>c657ee26-4ccb-4c3e-ab16-eed0a5ece457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2164026-4782-4ce3-8115-15391b97e9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstName compoundBorderBottom form-element__row input</value>
      <webElementGuid>6777cfe5-b0d2-4fb1-8ddf-5e9b0f012ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>153:1731;a</value>
      <webElementGuid>3d20a0d7-a6c0-4292-b86e-245950ba2f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c13b5e2a-5e34-45a5-9b34-3fc482e8e916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad72a7e4-6d5b-4ed4-82b7-86b749d79525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;149:1731;a&quot;)</value>
      <webElementGuid>149bcc89-0727-4578-9181-8ef09a66da6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='149:1731;a']</value>
      <webElementGuid>5a31dadb-630c-40ec-9634-d57e3aee553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>bc28209b-e8d2-4b00-af85-d86b2dfc60dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
